/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.kyori.adventure.platform.bukkit)
    api(libs.net.kyori.adventure.text.minimessage)
    api(libs.com.github.cryptomorin.xseries)
    api(libs.javax.annotation.javax.annotation.api)
    api(libs.com.google.code.findbugs.jsr305)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.net.dmulloy2.protocollib)
}

group = "com.codingguru"
version = "2.7.0-MC26"
description = "inventorystacks"
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.release.set(25)
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
