/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    alias(libs.plugins.shadow)
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.kyori.adventure.platform.bukkit)
    api(libs.net.kyori.adventure.text.minimessage)
    api(libs.com.github.cryptomorin.xseries)
    api(libs.javax.annotation.javax.annotation.api)
    api(libs.com.google.code.findbugs.jsr305)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.net.dmulloy2.protocollib)
}

group = "com.codingguru"
version = "2.7.2-MC26"
description = "inventorystacks"
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.release.set(25)
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    archiveClassifier.set("")
    mergeServiceFiles()
    exclude("META-INF/license/**")
    exclude("META-INF/*")
    exclude("META-INF/maven/**")
    exclude("LICENSE")
    exclude("NOTICE")
    exclude("/*.txt")
    exclude("build.properties")
    exclude("com/cryptomorin/xseries/XEnchantment*")
    exclude("com/cryptomorin/xseries/XEntityType*")
    exclude("com/cryptomorin/xseries/XEntity*")
    exclude("com/cryptomorin/xseries/XSound*")
    exclude("com/cryptomorin/xseries/XBiome*")
    exclude("com/cryptomorin/xseries/NMSExtras*")
    exclude("com/cryptomorin/xseries/NoteBlockMusic*")
    exclude("com/cryptomorin/xseries/SkullCacheListener*")
    exclude("com/cryptomorin/xseries/art/**")
    exclude("com/cryptomorin/xseries/profiles/**")
    exclude("com/cryptomorin/xseries/reflection/**")
    exclude("com/cryptomorin/xseries/particles/**")
    exclude("com/cryptomorin/xseries/messages/**")
    exclude("com/cryptomorin/xseries/inventory/**")
    exclude("com/cryptomorin/xseries/paper/**")
    exclude("com/cryptomorin/xseries/XTag*")
    exclude("com/cryptomorin/xseries/XWorldBorder*")
}

tasks.jar {
    enabled = false
}

tasks.build {
    dependsOn(tasks.shadowJar)
}
